title: Using Github Pages for code documentation
author: Damien Burns
email: mechjagger@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Using the following Github page site to manage code related documentation and standards for PHP.

github_username: mechjagger

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
